= Logging Discussion Document =
:toc:
:tocplacement!:
toc::[]

:sectnums:
:sectnumlevels: 4

After an introductory discussion setting the scene, "what logging _is_", "what logging _is not_", and some chat, we expand on the terms and definitions in the scope and try to form a set of parameters for defining what we want from logging and how we might go about getting it.

== Preamble and Introduction
There is a circular dependency between what we mean by the term 'logging' and what problem logging is intended to solve. I propose restricting the meaning of the term in the context of this document and to attempt to tie the two together in a coherent and useful way.

Put very simply, 'logging' is the use of print statements by a programmer for the benefit of the programmer.

=== Audience ===
This is for 3GL and 4GL programmers writing server side business software; languages such as C, C++, C#, Java, Go, Python, Rust. 

Safety or time critical applications are not within scope

=== Ambit ===
Logging here refers to the output of a server process that is


. the output of an
.. identifiable,
.. discretionary,
.. programmer added,
.. source code call to some function,
.. with the intention of creating a durable record of an event or state
. output to a streaming service such as a file system, network, or DBMS
. not part of the UI
. not covered by a requirement in a specification
. text in ASCII or UTF-8


Log files are expected to be used by a programmer or a system operator either during development of software or a surprise non-conformance issue (a crash or other failure).


=== Logging Disambiguation
Programmers and others use the word 'logging' in many ways, most of which are both vague and ambiguous. Before offering help on logging choices it is as well to reduce the vagueness and ambiguity.
With that in mind, this section discusses what is, and what is not, meant here by 'logging'.
There is also a small note on the origin of the term.

=== Exclusions
Logs of the following kind are not part of this discussion:

. Database Logs (transaction logs)
. Access Control Logs (logins)
. Functional Logs such as telemetry data, weather, bore hole, and so on (borehole logs)
. Critical information for System Operators or Administrators (exceptions and failures)


=== Best Practice?
Not wishing to hide behind thought-stopping clich&#233;s we shall not discuss 'best practice' beyond refusing to entertain the idea and providing a word or two on why.

For there to exist any 'best practice' there must be:

. specific, explicit requirements that must be met
. proof, or at least substantial evidence that the above requirements match the requirements at hand
. an enumeration of all practices that could apply
. an agreed, non-contentious, metric, that demonstrably provides an order relation on all practices
. proof or at least substantial evidence that the 'best practice' has been assessed by the agreed metric and found to be superior to all other practices



=== Etymology
.Etymology
[%collapsible]
====
As an aside and for interest only, a brief description of how the word 'log' came to be so confused.

A sailor would throw a wood log overboard near the bow of a ship and the time it took to pass a given point aft would indicate the speed of the ship through the water.
Over time, this became a special purpose piece of wood attached to a knotted rope that would be payed out for a set time and the number of knots that were payed out indicated the speed, in knots, of the ship.

The speed would be recorded in a log book and would help reckon the distance travelled. Note that this kind of log book is unrelated to a book of logs, or log tables; 'log' there, coming from 'logarithm' with an entirely different etymology.
====


=== The logging context
Almost all server process _can_ be user configured to create text output relating to the ongoing life of the process in such a way that it does not alter the function of the process.
Programmers of user applications have always added some print statements to their code for their own benefit, for example to help diagnose a problem or to help understand how to make a change.
So as a programmer you may be looking for information about logging that may make your coding life easier.
However, logging is not well covered, if at all, in the serious accademic literature. For example, there is almost nothing in any of the following:

* "Design Patterns"footnote:["Design Patterns: elements of reusable object-oriented software" Gamma, Erich, et al] 
* "Structure and Interpretation of Computer Programs"footnote:["Structure and Interpretation of Computer Programs" Abelson, Harold et al]
* "The Mythical Man-month"footnote:["The Mythical Man-month" Brooks, Frederick P. Jr]
* "No Silver Bullet"footnote:["No Silver Bullet" Brooks, Frederick P. Jr]
* "The Elements of Programming Style"footnote:["The Elements of Programming Style" Kernighan, Brian]

This small list in this respect is representative of so many written about software in the large or small, and from practical or theoretical points of view. So "Where Angels Fear to Tread" many far less well qualified commentators and influencers have rushed in.

There are "N best practices for logging", "Logging Patterns", and of course "Logging Anti-Patterns", "Patterns for Micro-Services Enterprise Logging", and so on. 

Much of the advice is hopeless or actually harmful. 

=== Purpose of this document
I hope that this document provides a quick, curated, entry point to help programmers select, build, and configure, their logging solution so that it works for them and those they work with.
It is not intended to be a specification for the design of libraries and services to meet all needs without the programmer having to think for themselves. There are other sources of that 'information' - good luck.

== Expanding the preamble

=== The Ambit
What follows is an explanation of the restrictions shown in the Ambit section above. Some restrictions may raise eyebrows but I hope I can convince you that they are mostly useful.


==== identifiable
It is desireable to be able to match some information in a log stream with a single place in the source code responsible for the output. The log statement should be part of the source code and not automatically added by an instrumentation process as part of the tool chain.
Like assertions, log statements tell developers something about the code. They form an important part of the implementation but not part of the design.

==== discretionary
The programmer chooses where to place log statements. Like comments, each log statement in the code should carry its weight. Whether the log statement actually produces output each time the line is reached is also discretionary and can be controlled by environmental, compile time, or run time conditions.

Postmortem dumps are not considered logs.

==== programmer added
It is up to the programmer to add log statements. This might seem obvious but there are many languages and tools that offer tracing facilities to monitor, either transiently, or durably, the execution path of a program. Such log output is not considered here.

==== source code call to some function ====
It is the job of source code and not the byte code, or P code, interpreter to generate log output. It is also to be expected that a user defined function be called and not a language feature.

Stack traces exist in a middle ground here. When created by function call they are within the letter of these restrictions but are not within its spirit.

==== with the intention of creating a durable record of an event or state
Programmer intention is perhaps the most important aspect to logging. Some benefit to the programmer must have been forseen by adding a line of code that is not necessary to meet functional requirements. I am not refering here to 'shotgun' logging.

The record could simply show that a certain line in the code had been executed and such would constitute an event. This may be sufficient but often a breakpoint would have achieved the same effect with an attended execution of the process. For unattended running, it is more likely that some execution state be revealed.

==== output to a streaming service such as a file system, network, or DBMS ====
Log output should be durable so that it can be reviewed in the light of some surprise non-conformance event.
Typically the code writing a log message will inherit some log stream from a containing program or framework and 

Calls to external services such as contacting an MTA via IMAP would not constitute logging.

==== not part of the UI ====
Flashing screens and beeps are not logging.

Client processes can log too but these days, for better or worse, UI means a browser and client logging should not be visible to the user.

==== not covered by a requirement in a specification ====
Output required to conform to a requirement is clearly not discretionary. It would properly be regarded as normal output of the program and as essential as the UI and any other form of output specified in the requirements.

==== text in ASCII or UTF-8 ====
This may seem arbitrary or over restrictive but the two situations where a programmer would wish to use the log output, the only reason to have any at all, are ones where limited viewing and searching facilities are to be expected.

Special purpose log viewers are not a welcome requirement when under pressure to mend broken software in a production environment.

Many very well known and understood text processing tools exist and are readily available on development and production servers. ASCII is the life blood of Unix and line oriented files are practically de rigueur.


== Development Context
Although some programmers may have only to consider their own code, most will be working in a heterogeneous environment. If you have constraints over some or all technical choices, you may still have scope to choose how you use those libraries and subsystems.

You will most likely be writing code for a system that has applications running on operating systems from more than one vendor, in more than one language, and libraries from more than source including open source and multiple commercial vendors.



=== Development Problem
Usually, a solution is proposed to solve a problem and is assessed against that problem. 
However, for Logging it seems that even a na&iuml;ve problem description is awkward. 
You cannot know, in advance, what exceptional error situation will occur and what state and path data you would like to have at your disposal to assist with your problem resolution. 
In short, if you knew what was going to go wrong you would do something to prevent it.


=== Some silly advice
Logs must be namespaced and have an assigned severity level (e.g. trace, debug, info, warn, error, fatal).


